# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: docker build csharp
        run: |
          docker build ./c# -t yzwdroid/csharp:1.0.0

      - name: docker build nodejs
        run: |
          docker build ./nodejs -t yzwdroid/nodejs:1.0.0
      - name: docker build python
        run: |
          docker build ./python -t yzwdroid/python:1.0.0

